### PR TITLE
Use Internal npm Registry

### PR DESCRIPTION
**Pull request by dhhuynh2**
We have a new internal npm proxy registry that utilizes Verdaccio to cache packages. This PR updates the necessary files to utilize the registry.

https://github.com/powerhome/npm-registry

https://portal.powerapp.cloud/docs/default/system/npm-registry

### CODE REVIEW

**Comment by xjunior** [comment]
@dhhuynh2 do we have plans to deploy a rubygems registry as well?

**Comment by dhhuynh2** [comment]
> @dhhuynh2 do we have plans to deploy a rubygems registry as well?

@xjunior Not at the moment, as far as I know. The immediate concern for the npm registry was fontawesome bandwidth quota issues, so that was our focus. Feel free to chip in if needed @benlangfeld @ryanmrodriguez .

**Review by benlangfeld — COMMENTED** [review]
This is an open source project. It doesn't use fontawesome, does it? If not, is there a benefit to using our registry mirror that outweighs cutting off the open-source users?

**Comment by dhhuynh2** [comment]
> This is an open source project. It doesn't use fontawesome, does it? If not, is there a benefit to using our registry mirror that outweighs cutting off the open-source users?

Sorry - I missed this comment. Wasn't aware this was a public project. And yes, I had mistaken fontawesome usage, it's using free, not pro. With both of those in mind, going to close this PR.

**Pull request closed without merging**
